CALL_GRAPHICS      
    LDX #$60 	; IOCB #6 FOR GRAPHICS
  	LDA #CLOSE 	; CLOSE #6 FOR SAFETY (CAN'T  ;OPEN AN ALREADY OPEN DEVICE)
  	STA ICCOM,X
  	JSR CIOV
    LDA #$60
    STA $6A
  	LDA #OPEN
  	STA ICCOM,X
  	LDA # <FNAME 	; FILENAME IS S:
  	STA ICBAL,X
  	LDA # >FNAME
  	STA ICBAH,X
  	LDA #0  	; GR. MODE
  	STA ICAUX2,X
  	AND #$F0 	; KEEP UPPER NIBBLE FOR FULLSCREEN
  	;  	& NO SCREEN ERASE FLAGS(+16 & +32)

*O.S. FULL SCREEN FLAG IS THE OPPOSITE OF THE WAY BASIC USES IT.
*i.e. +16 = SPLIT SCREEN NOT FULL SCREEN
  	EOR #$10 	; FLIP-FLOP IT LIKE BASIC
  	ORA #$0C 	; OPEN S: FOR READING & WRITING
  	STA ICAUX1,X
  	JSR CIOV 	; GO DO IT IT WILL RTS FROM THERE
  	RTS
FNAME
  	dta $53,$3A,$9B
    ORG $2E2
    DTA <$3F00,>$3F00
